pod 'Facebook-iOS-SDK', '~> 3.15'
pod 'VLBCameraView', :git => 'https://github.com/bvallelunga/VLBCameraView.git'
pod 'CHTTextView', '~> 0.1'
pod 'THContactPicker', '~> 0.0'
pod 'iPhoneContacts', '~> 0.0'